# Generated by Django 5.2.1 on 2025-05-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Identifiant unique de la facture', max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant total de la facture (en euros)', max_digits=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True, help_text='Date a laquelle la facture a été émise')),
                ('statut_paiement', models.CharField(choices=[('envoyée', 'Envoyée'), ('payée', 'Payée'), ('en_retard', 'En retard')], default='envoyee', help_text='Statut du paiement de la facture', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Remarques sur la facture, par exemple les motifs du retard de paiement')),
                ('client', models.ForeignKey(help_text='Client concerné par la facture', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
                ('projet', models.ForeignKey(help_text='Projet associé à la facture', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='projets.projet')),
            ],
        ),
    ]
