services:
  - type: web
    name: mini-crm-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: gunicorn mini_crm.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: mini-crm-lezi.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: mini-crm-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mini-crm-redis
          property: connectionString
    dependsOn:
      - name: mini-crm-db
      - name: mini-crm-redis

  - type: redis
    name: mini-crm-redis
    plan: free
    ipAllowList: []

databases:
  - name: mini-crm-db
    plan: free
    databaseName: mini_crm
    user: mini_crm_user
