# Generated by Django 5.2.1 on 2025-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Societe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=20)),
                ("ville", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("siret", models.CharField(blank=True, max_length=20)),
                ("tva", models.CharField(blank=True, max_length=30)),
                ("iban", models.CharField(blank=True, max_length=40)),
                ("bic", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
